name: Synapse CI-CD

on:
  push:
    branches:
      - dev2  # trigger on dev2 updates

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    steps:
      # Checkout dev2 (source artifacts)
      - name: Checkout dev2 branch
        uses: actions/checkout@v4
        with:
          ref: dev2

      # Checkout prod3 (ARM templates)
      - name: Checkout prod3 branch (ARM templates)
        uses: actions/checkout@v4
        with:
          ref: prod3
          path: prod3-templates

      # Azure login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_SECRET }}

      # Deploy to production
      - name: Deploy Synapse to Prod
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ fromJSON(secrets.AZURE_SECRET).subscriptionId }}
          resourceGroupName: RGproduction
          template: prod3-templates/testingenvfabic/TemplateForWorkspace.json
          parameters: prod3-templates/testingenvfabic/TemplateParametersForWorkspace.json
