name: Synapse CI-CD

on:
  push:
    branches:
      - dev2   # or dev, depending on where you publish

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_SECRET }}

      - name: Deploy Synapse to Prod
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ fromJSON(secrets.AZURE_SECRET).subscriptionId }}
          resourceGroupName: my-prod-rg
          template: dev2/testingenvfabic/TemplateForWorkspace.json
          parameters: dev2/testingenvfabic/TemplateParametersForWorkspace.json


